### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by UaleWonka** [Orange-OpenSource/conllueditor#31]
Hi, 

I am using Windows 10, and I launched ConlluEditor with the jar in the .zip of the latest release.

I have found 2 probable bugs:

1. I cannot launch the validator: it gives me this error: 

`Validator error: Cannot run program "C:\UD\tools\validate.py": CreateProcess error=193, %1 non è un'applicazione di Win32 valida`

2. When I try a compose or a split operation, it doesn't modify the sentence text and it doesn't work anymore. 

`|incoherent "# text" and forms: «Tormenta undique conquiri et frumentum mitti auxilia adduci iubet.» ≠ «Tormenta undique conquiri etfrumentum mitti auxilia adduci iubet.|`

When I use the sentsplit operation, it gives me this error too (and it cannot undo the operation):

`General error: Cannot invoke "String.charAt(int)" because the return value of "com.orange.labs.conllparser.ConllSentence.getText()" is null`

Thank you!

**Comment by jheinecke** [comment]
Hi,
For the first error, it looks like your windows has no python installed. Since `C:\UD\tools\validate.py` is a python programme, you should install python. If it _is_installed, maybe changing it to `python C:\UD\tools\validate.py` (in the validator script) works?
I'll have a look in the compose/split problem. Can you post the sentence and the operation which caused this bug?

**Comment by jheinecke** [comment]
In fact the `sentsplit` operation (and the `compose` operation) do not modify the `# text ...` line of the sentence. Once the sentence is split, you should use the `edit metadata` button to adapt the text.

**Comment by Stormur** [comment]
> In fact the `sentsplit` operation (and the `compose` operation) do not modify the `# text ...` line of the sentence. Once the sentence is split, you should use the `edit metadata` button to adapt the text.

Is this a new behaviour? Or specific to the precompiled jar? I do not remember having issues with this :thinking:

**Comment by jheinecke** [comment]
It is :-( since the `# text` is the original text, and modifiying it automatically without asking the user could cause errors, I stopped this. I could add it as an option though.

**Comment by Stormur** [comment]
Ah! Yes, I think that many would opt for this, in my experience it has always been a sensible thing.

At least when doing sentence splitting, I think it is no use of keeping the split tokens together with their old sentence (this is part of the bug reported by the original poster).

**Comment by jheinecke** [comment]
OK, I agree, I will update the `# text = ...` line after `sentsplit`, `sentjoin` and `compose` operations, as users actively change the tokenisation, and the original sentence is of no importance any more

**Comment by UaleWonka** [comment]
> Hi, For the first error, it looks like your windows has no python installed. Since `C:\UD\tools\validate.py` is a python programme, you should install python. If it _is_installed, maybe changing it to `python C:\UD\tools\validate.py` (in the validator script) works? I'll have a look in the compose/split problem. Can you post the sentence and the operation which caused this bug?

I modified the validator script as you suggested and now it works. Thank you!

About the second issue, here are the two cases:

Sentence: `Bello Alexandrino conflato Caesar Rhodo atque ex Syria Ciliciaque omnem classem arcessit.`
Operation: `split 9`
Bug: `incoherent "# text" and forms: «Bello Alexandrino conflato Caesar Rhodo atque ex Syria Ciliciaque omnem classem     arcessit.» ≠ «Bello Alexandrino conflato Caesar Rhodo atque ex Syria Ciliciaque Ciliciaque omnem classem arcessit.|`

Here I can still move to the next sentence, but I cannot undo the operation.

Sentence: `(Quarum alterius rei copiam exiguam, alterius nullam omnino facultatem habebat.) Quod utrumque large palus praebere poterat.`
Operation: `sentsplit 15`
Bug: `incoherent "# text" and forms: «(Quarum alterius rei copiam exiguam, alterius nullam omnino facultatem habebat.) Quod utrumque large palus praebere poterat.» ≠ «(Quarum alterius rei copiam exiguam, alterius nullam omnino facultatem habebat.)|`

Here I cannot undo the operation ( it says me this: `General error: Cannot invoke "String.charAt(int)" because the return value of "com.orange.labs.conllparser.ConllSentence.getText()" is null`), nor I can move to next sentence (it says me this: `General error: Cannot invoke "String.charAt(int)" because the return value of "com.orange.labs.conllparser.ConllSentence.getText()" is null`)

Thank you again!

**Comment by UaleWonka** [comment]
I just noticed that I cannot undo anything. Even if I modify a dependency relation, when I try to undo it, it says me: 

`General error: Cannot invoke "String.charAt(int)" because the return value of "com.orange.labs.conllparser.ConllSentence.getText()" is null`

**Comment by jheinecke** [comment]
Hi, I just released version 2.22.0, which corrects this bug (and also gives the possibility to do shortcuts for values in the MISC column (@Stormur :-) )
you can either do `git pull` and `mvn install` or grab the V2.22.0 release

**Comment by UaleWonka** [comment]
> Hi, I just released version 2.22.0, which corrects this bug (and also gives the possibility to do shortcuts for values in the MISC column (@Stormur :-) ) you can either do `git pull` and `mvn install` or grab the V2.22.0 release

Thank you! Now the `sentsplit` and the `split` operations work.

I still have problems with the undo button. Whatever I do (modifying deprels, or using operations), I cannot undo them. 
It always says me: 

`General error: Cannot invoke "String.length()" because the return value of "com.orange.labs.conllparser.ConllSentence.getText()" is null`

The same error message pops out when I move to another sentence, and I try to read again the sentence I modified before.

**Comment by jheinecke** [comment]
I found an error in my unitary tests, so this bug got through. It should be OK now with V2.22.1

**Comment by UaleWonka** [comment]
> I found an error in my unitary tests, so this bug got through. It should be OK now with V2.22.1

Now it works perfectly.
Thank you for your support!

**Comment by UaleWonka** [comment]
> Hi, I just released version 2.22.0, which corrects this bug (and also gives the possibility to do shortcuts for values in the MISC column (@Stormur :-) ) you can either do `git pull` and `mvn install` or grab the V2.22.0 release

Sorry for bothering you again. 

I'm using the shortcuts in the MISC column, but when I use it on a node which already contains the annotation `SpaceAfter=No`, it deletes it and replace it with my annotation, thus leading to an error (`incoherent "# text" and forms`). 

Could you please help me?

**Comment by jheinecke** [comment]
Thanks for pointing me to this, it is corrected in V2.22.2 (`git pull && mvn install` or latest release)

**Comment by UaleWonka** [comment]
> Thanks for pointing me to this, it is corrected in V2.22.2 (`git pull && mvn install` or latest release)

Thank you!
